title: Plotter People
email: nornagon@nornagon.net
description: >-
  Plotter People is a meetup for creative coders and people interested in
  collaborating with robots to make art.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plotterpeople.github.io"
twitter_username: plotterpeople
github_username: plotterpeople

logo: /assets/img/pp_logo.png

markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
